import { type NodeData, NodeType } from './types';

export const NET_ARCHITECTURE_DATA: Record<number, NodeData> = {
  1: {
    id: 1,
    level: 0,
    gridX: 6,
    gridY: 1,
    type: NodeType.ENTRYPOINT,
    label: "Public Access",
    description: "External access terminal for Heywood Harbour.",
    content: "Initial jack-in point for the Heywood Harbour Management Corp. Limited public access functions.",
    dv: null,
    connections: [2],
    revealed: true,
  },
  2: {
    id: 2,
    level: 1,
    gridX: 6,
    gridY: 2,
    type: NodeType.PASSWORD,
    label: "Main Firewall",
    description: "Zetatech Sentinel v3.1 Firewall",
    content: "This corporate firewall blocks access to the main network. A standard Interface check is required to bypass it.",
    dv: 8,
    connections: [1, 3],
    revealed: false,
  },
  3: {
    id: 3,
    level: 2,
    gridX: 6,
    gridY: 3,
    type: NodeType.BRANCH,
    label: "Network Junction",
    description: "Main network router splitting into Security, Logistics, and Mainframe.",
    content: "From here, the NET architecture branches. Choose your path wisely.",
    dv: null,
    connections: [2, 4, 10, 14],
    revealed: false,
  },
  // Security Branch (Left)
  4: {
    id: 4,
    level: 3,
    gridX: 4,
    gridY: 4,
    type: NodeType.CONTROL_NODE,
    label: "Lobby Cameras",
    description: "Controls the camera feeds for the main lobby and entrances.",
    content: "Gain control to view, loop, or disable cameras in the primary access areas of the physical building.",
    dv: 10,
    connections: [3, 5],
    revealed: false,
  },
  5: {
    id: 5,
    level: 4,
    gridX: 2,
    gridY: 5,
    type: NodeType.BLACK_ICE,
    label: "Asp",
    description: "An anti-program ICE. Icon: A golden Egyptian cobra.",
    content: "This Black ICE is designed to destroy a netrunner's programs. It will attack any unauthorized programs it detects.",
    dv: null,
    connections: [4, 6],
    revealed: false,
  },
  6: {
    id: 6,
    level: 5,
    gridX: 2,
    gridY: 6,
    type: NodeType.PASSWORD,
    label: "Security Admin",
    description: "Secondary firewall protecting deep security systems.",
    content: "Higher-level access is required. Bypassing this will grant access to more sensitive security controls.",
    dv: 10,
    connections: [5, 7, 8],
    revealed: false,
  },
  7: {
    id: 7,
    level: 6,
    gridX: 1,
    gridY: 7,
    type: NodeType.CONTROL_NODE,
    label: "Berth Turrets",
    description: "Controls the automated defense turrets in Berths 1 through 4.",
    content: "Control of this node allows for aiming and firing of the heavy-duty automated turrets protecting high-value cargo.",
    dv: 12,
    connections: [6],
    revealed: false,
  },
  8: {
    id: 8,
    level: 6,
    gridX: 3,
    gridY: 7,
    type: NodeType.BLACK_ICE,
    label: "Killer",
    description: "An anti-program ICE. Icon: A robotic samurai with a glowing katana.",
    content: "A deadly program designed to derez other programs with extreme prejudice.",
    dv: null,
    connections: [6, 9],
    revealed: false,
  },
  9: {
    id: 9,
    level: 7,
    gridX: 3,
    gridY: 8,
    type: NodeType.FILE,
    label: "Patrol Roster",
    description: "Encrypted file containing security patrol schedules and routes.",
    content: "Successfully accessing this file reveals the exact movements and timings of all physical security patrols for the next 24 hours.",
    dv: 10,
    connections: [8],
    revealed: false,
  },
  // Logistics Branch (Right)
  10: {
    id: 10,
    level: 3,
    gridX: 8,
    gridY: 4,
    type: NodeType.FILE,
    label: "Shipping Manifests",
    description: "Publicly accessible, but sanitized, shipping manifests for Q1.",
    content: "Contains standard shipping data. High-value or sensitive cargo is not listed here.",
    dv: 6,
    connections: [3, 11],
    revealed: false,
  },
  11: {
    id: 11,
    level: 4,
    gridX: 10,
    gridY: 5,
    type: NodeType.CONTROL_NODE,
    label: "Crane Controls",
    description: "Controls for automated container cranes in Berths 5-8.",
    content: "Allows user to move, lock, or drop containers, potentially causing massive physical disruption or allowing for theft.",
    dv: 8,
    connections: [10, 12],
    revealed: false,
  },
  12: {
    id: 12,
    level: 5,
    gridX: 10,
    gridY: 6,
    type: NodeType.PASSWORD,
    label: "Logistics Admin",
    description: "Firewall for the logistics and cargo management subnet.",
    content: "Access to detailed, real-time cargo tracking and manifests.",
    dv: 8,
    connections: [11, 13],
    revealed: false,
  },
  13: {
    id: 13,
    level: 6,
    gridX: 11,
    gridY: 7,
    type: NodeType.FILE,
    label: "High-Value Cargo",
    description: "Specific manifest for special handling container #AE-34.",
    content: "Details the contents and destination of a high-value, off-ledger shipment. This is valuable intel.",
    dv: 10,
    connections: [12, 17],
    revealed: false,
  },
  // Mainframe Branch (Center)
  14: {
    id: 14,
    level: 5,
    gridX: 6,
    gridY: 5,
    type: NodeType.BLACK_ICE,
    label: "Hellhound",
    description: "A deadly anti-personnel ICE. Icon: A huge, black metal wolf with glowing white eyes.",
    content: "This ICE is designed to directly attack the Netrunner's brain, inflicting bio-feedback damage. Extremely dangerous.",
    dv: null,
    connections: [3, 15],
    revealed: false,
  },
  15: {
    id: 15,
    level: 6,
    gridX: 6,
    gridY: 6,
    type: NodeType.PASSWORD,
    label: "Mainframe Access",
    description: "Military-grade ICE wall protecting the central data fortress.",
    content: "This is the final layer of protection before the system's core. A significant challenge for any runner.",
    dv: 12,
    connections: [14, 16],
    revealed: false,
  },
  16: {
    id: 16,
    level: 7,
    gridX: 6,
    gridY: 8,
    type: NodeType.FILE,
    label: "The 'Off-Ledger'",
    description: "The corporation's hidden, illegal shipping manifest.",
    content: "This is the prize. Complete, unredacted data on all unsanctioned cargo, including weapons, tech, and personnel smuggling.",
    dv: 12,
    connections: [15, 17],
    revealed: false,
  },
  17: {
    id: 17,
    level: 8,
    gridX: 8,
    gridY: 9,
    type: NodeType.CONTROL_NODE,
    label: "Harbor Master",
    description: "System-wide master control.",
    content: "Accessing this node grants temporary root access to the entire Heywood Harbour network, allowing shutdown of all security measures.",
    dv: 12,
    connections: [13, 16],
    revealed: false,
  }
};