import { type NodeData, NodeType } from './types';

// Narrative: The netrunner is trying to gain access to useful controls and data 
// for infiltrating a cargo ship named "MS Maladia" which arrives at the harbour at 20:00h.

export const NET_ARCHITECTURE_DATA: Record<number, NodeData> = {
  // LVL 0-2: Entry
  1: {
    id: 1,
    level: 0,
    gridX: 11,
    gridY: 2,
    type: NodeType.ENTRYPOINT,
    label: "Public Access",
    description: "External access terminal for Heywood Harbour.",
    content: "Initial jack-in point for the Heywood Harbour Management Corp. Target: MS Maladia, ETA 20:00h. Find manifests, disable security.",
    dv: null,
    connections: [2],
    revealed: true,
  },
  2: {
    id: 2,
    level: 1,
    gridX: 11,
    gridY: 4,
    type: NodeType.PASSWORD,
    label: "Main Firewall",
    description: "Zetatech Sentinel v3.1 Firewall protecting the corporate network.",
    content: "This corporate firewall blocks access to the main network. A standard Interface check is required to bypass it.",
    dv: 8,
    connections: [1, 3],
    revealed: false,
  },
  3: {
    id: 3,
    level: 2,
    gridX: 11,
    gridY: 6,
    type: NodeType.BRANCH,
    label: "Network Junction",
    description: "Main network router splitting into Security, Logistics, and Mainframe.",
    content: "From here, the NET architecture branches. Security (left), Logistics (right), Mainframe (center). Choose your path wisely.",
    dv: null,
    connections: [2, 4, 10, 18],
    revealed: false,
  },
  // Security Branch (Left)
  4: {
    id: 4,
    level: 3,
    gridX: 8,
    gridY: 8,
    type: NodeType.CONTROL_NODE,
    label: "Lobby Cameras",
    description: "Controls the camera feeds for the main lobby and entrances.",
    content: "Gain control to view, loop, or disable cameras in the primary access areas of the physical building.",
    dv: 10,
    connections: [3, 5],
    revealed: false,
  },
  5: {
    id: 5,
    level: 4,
    gridX: 5,
    gridY: 10,
    type: NodeType.CONTROL_NODE,
    label: "Perimeter Fences",
    description: "Controls for the electrified perimeter fences around the berths.",
    content: "Disabling this will create an unguarded entry point for a physical infiltration team.",
    dv: 9,
    connections: [4, 6, 7],
    revealed: false,
  },
  6: {
    id: 6,
    level: 5,
    gridX: 2,
    gridY: 12,
    type: NodeType.BLACK_ICE,
    label: "Asp",
    description: "An anti-program ICE. Icon: A golden Egyptian cobra.",
    content: "This Black ICE is designed to destroy a netrunner's programs. It will attack any unauthorized programs it detects.",
    dv: null,
    connections: [5, 8],
    revealed: false,
  },
  7: {
    id: 7,
    level: 5,
    gridX: 8,
    gridY: 12,
    type: NodeType.PASSWORD,
    label: "Security Admin",
    description: "Secondary firewall protecting deep security systems.",
    content: "Higher-level access is required. Bypassing this will grant access to more sensitive security controls.",
    dv: 10,
    connections: [5, 9],
    revealed: false,
  },
  8: {
    id: 8,
    level: 6,
    gridX: 2,
    gridY: 14,
    type: NodeType.CONTROL_NODE,
    label: "Drone Control",
    description: "Controls the automated security drones patrolling the harbour.",
    content: "Hijack drone patrol routes, access their live feeds, or ground them entirely.",
    dv: 11,
    connections: [6, 31],
    revealed: false,
  },
  9: {
    id: 9,
    level: 6,
    gridX: 8,
    gridY: 14,
    type: NodeType.FILE,
    label: "Patrol Roster",
    description: "Encrypted file containing security patrol schedules and routes.",
    content: "Successfully accessing this file reveals the exact movements and timings of all physical security patrols for the next 24 hours.",
    dv: 10,
    connections: [7, 32],
    revealed: false,
  },
  // Logistics Branch (Right)
  10: {
    id: 10,
    level: 3,
    gridX: 14,
    gridY: 8,
    type: NodeType.FILE,
    label: "Shipping Manifests",
    description: "Publicly accessible, but sanitized, shipping manifests for Q1.",
    content: "Contains standard shipping data. The MS Maladia is listed, but its high-value cargo is not detailed here.",
    dv: 6,
    connections: [3, 11],
    revealed: false,
  },
  11: {
    id: 11,
    level: 4,
    gridX: 17,
    gridY: 10,
    type: NodeType.CONTROL_NODE,
    label: "Crane Controls",
    description: "Controls for automated container cranes in Berths 5-8.",
    content: "Allows user to move, lock, or drop containers, potentially causing a distraction or blocking security.",
    dv: 8,
    connections: [10, 12, 13],
    revealed: false,
  },
  12: {
    id: 12,
    level: 5,
    gridX: 20,
    gridY: 12,
    type: NodeType.BLACK_ICE,
    label: "Wisp",
    description: "An anti-program ICE. Icon: A flickering ball of white light.",
    content: "Fast and elusive, a Wisp attempts to derez a runner's utility programs before they can be used.",
    dv: null,
    connections: [11, 14],
    revealed: false,
  },
  13: {
    id: 13,
    level: 5,
    gridX: 14,
    gridY: 12,
    type: NodeType.PASSWORD,
    label: "Logistics Admin",
    description: "Firewall for the cargo management subnet.",
    content: "Access to detailed, real-time cargo tracking and manifests.",
    dv: 8,
    connections: [11, 15],
    revealed: false,
  },
  14: {
    id: 14,
    level: 6,
    gridX: 20,
    gridY: 14,
    type: NodeType.CONTROL_NODE,
    label: "RT Cargo Tracking",
    description: "Real-time positional data for all incoming vessels.",
    content: "Pinpoints the MS Maladia's current position, speed, and exact ETA. Can also be used to create ghost signals.",
    dv: 9,
    connections: [12, 33],
    revealed: false,
  },
  15: {
    id: 15,
    level: 6,
    gridX: 14,
    gridY: 14,
    type: NodeType.FILE,
    label: "Warehouse 13 Inv.",
    description: "Inventory file for the temporary storage warehouse at Berth 7.",
    content: "Shows what's currently stored and what's scheduled for offload from the Maladia. Useful for creating a cover.",
    dv: 8,
    connections: [13, 34],
    revealed: false,
  },
  // Mainframe Branch (Center)
  18: {
    id: 18,
    level: 4,
    gridX: 11,
    gridY: 10,
    type: NodeType.BLACK_ICE,
    label: "Hellhound",
    description: "A deadly anti-personnel ICE. Icon: A huge, black metal wolf with glowing white eyes.",
    content: "This ICE is designed to directly attack the Netrunner's brain, inflicting bio-feedback damage. Extremely dangerous.",
    dv: null,
    connections: [3, 19],
    revealed: false,
  },
  19: {
    id: 19,
    level: 5,
    gridX: 11,
    gridY: 12,
    type: NodeType.PASSWORD,
    label: "Mainframe Access",
    description: "Military-grade ICE wall protecting the central data fortress.",
    content: "This is the final layer of protection before the system's core. A significant challenge for any runner.",
    dv: 12,
    connections: [18, 20],
    revealed: false,
  },
  20: {
    id: 20,
    level: 6,
    gridX: 11,
    gridY: 14,
    type: NodeType.BRANCH,
    label: "Data Fortress Core",
    description: "The heart of the Heywood data network.",
    content: "The core branches again, leading to sensitive corporate data. The Harbor Master control is likely beyond this point.",
    dv: null,
    connections: [19, 21, 22],
    revealed: false,
  },
  21: {
    id: 21,
    level: 7,
    gridX: 9,
    gridY: 16,
    type: NodeType.FILE,
    label: "Employee Records",
    description: "Full personnel files for all harbour employees.",
    content: "Contains schedules, security clearances, and potential blackmail material on key personnel.",
    dv: 10,
    connections: [20, 23],
    revealed: false,
  },
  22: {
    id: 22,
    level: 7,
    gridX: 13,
    gridY: 16,
    type: NodeType.FILE,
    label: "Financial Ledgers",
    description: "The corporation's hidden, illegal shipping manifests.",
    content: "This is the prize. Unredacted data on all unsanctioned cargo, including who paid for the MS Maladia's special cargo.",
    dv: 12,
    connections: [20, 24],
    revealed: false,
  },
  23: {
    id: 23,
    level: 8,
    gridX: 9,
    gridY: 18,
    type: NodeType.BLACK_ICE,
    label: "Liche",
    description: "A powerful anti-personnel ICE. Icon: A skeletal figure in rotting robes.",
    content: "A master of illusion and misdirection, a Liche can trap a Netrunner in a simulated reality, frying their brain while they're lost.",
    dv: null,
    connections: [21, 25],
    revealed: false,
  },
  24: {
    id: 24,
    level: 8,
    gridX: 13,
    gridY: 18,
    type: NodeType.BLACK_ICE,
    label: "Killer",
    description: "An anti-program ICE. Icon: A robotic samurai with a glowing katana.",
    content: "A deadly program designed to derez other programs with extreme prejudice.",
    dv: null,
    connections: [22, 25],
    revealed: false,
  },
  25: {
    id: 25,
    level: 9,
    gridX: 11,
    gridY: 20,
    type: NodeType.CONTROL_NODE,
    label: "Harbor Master",
    description: "System-wide master control.",
    content: "Accessing this grants temporary root access to the entire network, allowing shutdown of all security measures for the Maladia's arrival.",
    dv: 12,
    connections: [23, 24, 26],
    revealed: false,
  },
  26: {
    id: 26,
    level: 10,
    gridX: 11,
    gridY: 22,
    type: NodeType.CONTROL_NODE,
    label: "System Purge",
    description: "Erases all system logs for the last hour.",
    content: "A one-shot opportunity to wipe your entry traces. Using it will cause a system reboot in 5 minutes, kicking you out.",
    dv: 10,
    connections: [25],
    revealed: false,
  },
  // DEEP NODES
  31: {
    id: 31,
    level: 7,
    gridX: 5,
    gridY: 16,
    type: NodeType.CONTROL_NODE,
    label: "Berth Turrets",
    description: "Controls the automated defense turrets in Berths 5 through 8.",
    content: "Control of this node allows for aiming and firing of the heavy-duty automated turrets protecting high-value cargo.",
    dv: 12,
    connections: [8, 32],
    revealed: false,
  },
  32: {
    id: 32,
    level: 7,
    gridX: 5,
    gridY: 14,
    type: NodeType.FILE,
    label: "Security Comms Log",
    description: "Live feed and logs of the security radio channels.",
    content: "Monitor guard movements and response times in real-time. Identify distracted or isolated patrols.",
    dv: 10,
    connections: [9, 31],
    revealed: false,
  },
  33: {
    id: 33,
    level: 7,
    gridX: 17,
    gridY: 16,
    type: NodeType.FILE,
    label: "Docking Bay Assign.",
    description: "File detailing which berth the MS Maladia will be assigned to.",
    content: "Knowing the exact docking location is critical for planning the physical intercept.",
    dv: 9,
    connections: [14, 34, 35],
    revealed: false,
  },
  34: {
    id: 34,
    level: 7,
    gridX: 17,
    gridY: 14,
    type: NodeType.CONTROL_NODE,
    label: "Auto-Docking System",
    description: "Controls the automated mooring arms and gangways.",
    content: "'Malfunctioning' equipment could create the perfect window for an infiltration team to board the MS Maladia.",
    dv: 10,
    connections: [15, 33],
    revealed: false,
  },
  35: {
    id: 35,
    level: 8,
    gridX: 18,
    gridY: 18,
    type: NodeType.BLACK_ICE,
    label: "Pit Scorpion",
    description: "An anti-personnel ICE. Icon: A chrome scorpion with a sparking tail.",
    content: "This ICE 'stings' the runner with painful but non-lethal biofeedback, reducing their Interface skill temporarily.",
    dv: null,
    connections: [33, 36],
    revealed: false,
  },
  36: {
    id: 36,
    level: 9,
    gridX: 15,
    gridY: 18,
    type: NodeType.FILE,
    label: "MS Maladia Manifest",
    description: "The specific, unredacted manifest for the target vessel.",
    content: "This is it. The detailed list of the 'special cargo' in container AE-34 aboard the Maladia. Your primary objective.",
    dv: 12,
    connections: [35],
    revealed: false,
  },
};
